Test order of execution, closes #1343
WebAssembly/spec pull request #1346
Opened 2021-07-18 16:25 UTC by SoniEx2

2021-10-07 22:23 UTC, ngzhian commented on test/core/order_of_execution.wast
> +(assert_trap (invoke "div-by-zero") "integer divide by zero")
LGTM, maybe a comment here describing what we want these tests to catch? Along the lines of
"Traps have side effect and instructions follow them should not run, optimizations must preserve this side-effect"

2021-10-08 06:28 UTC, rossberg requested changes
Except for a few legacy exceptions, the test suite is structured around individual constructs (or groups thereof). Instead of introducing a new file with a random selection of things, can you put each test into the appropriate file for the affected construct?

2022-08-04 08:16 UTC, rossberg commented
@SoniEx2, this PR is stale, do you still intend to land it?

2022-08-04 08:57 UTC, SoniEx2 commented
kinda haven't had the time to work on this anymore, sorry.

2022-08-04 08:57 UTC, closed without merging