Fix signature of `table.grow` in instructions index
WebAssembly/spec pull request #1349
Opened 2021-07-22 21:14 UTC by fitzgen

It pushes the old table size on success or `-1` on failure.

@rossberg, please take a look.

2021-07-22 21:15 UTC, fitzgen commented
Just went and linked my github account with my w3c account. Not sure how to retrigger the check.

2021-07-23 09:44 UTC, rossberg approved these changes
Thanks! LGTM modulo missing backslash.

2021-07-23 09:44 UTC, rossberg commented on document/core/appendix/index-instructions.rst
> +:math:`\TABLEGROW~x`                       :math:`\hex{FC}~\hex{0F}`  :math:`[t~\I32] \to [I32]`                     :ref:`validation <valid-table.grow>`     :ref:`execution <exec-table.grow>`
```suggestion
:math:`\TABLEGROW~x`                       :math:`\hex{FC}~\hex{0F}`  :math:`[t~\I32] \to [\I32]`                     :ref:`validation <valid-table.grow>`     :ref:`execution <exec-table.grow>`                             
```

2021-07-23 09:46 UTC, rossberg requested changes
Oh, sorry, actually, this is a generated file. You'll need to change gen-index-instructions.py and then rerun it.

2021-07-26 16:15 UTC, fitzgen commented
Updated the script and re-ran it.

2021-07-26 16:35 UTC, rossberg approved these changes
Thanks!

2021-07-26 16:38 UTC, fitzgen commented
Thanks for review!

Note: I don't have commit access to this repo, so I'll need your help actually landing this.

2021-07-26 16:41 UTC, rossberg commented
@fitzgen, IPR check seems to fail, have you registered with the CG under the same email?

2021-07-26 16:45 UTC, fitzgen commented
Yes, I've connected my github account, but I did it after opening this PR. Not sure how to re-run that check.

2021-07-26 16:55 UTC, rossberg commented
(I'm overriding IPR check since the fix is trivial.)

2021-07-26 16:55 UTC, merged